// Generated by spider on 2022-12-18 01:46:04.675822

part of 'resources.dart';

class Images {
  Images._();

  static const String appbarBackgroundImage =
      'assets/images/appbar_background_image.png';
  static const String justImage = 'assets/images/just_image.png';
  static const String something = 'assets/images/something.png';
}
