// Generated by spider on 2022-12-15 22:59:39.784520

part of 'resources.dart';

class Images {
  Images._();

  static const String appbarBackgroundImage =
      'assets/images/appbar_background_image.png';
  static const String justImage = 'assets/images/just_image.png';
}
