// Generated by spider on 2022-12-13 16:17:04.534415

part of 'resources.dart';

class Images {
  Images._();

  static const String appbarBackgroundImage =
      'assets/images/appbar_background_image.png';
}
