// Generated by spider on 2022-12-18 01:46:04.850721

part of 'resources.dart';

class Svgs {
  Svgs._();

  static const String arrowLeft = 'assets/svgs/arrow-left.svg';
  static const String arrowUp = 'assets/svgs/arrow-up.svg';
  static const String copy = 'assets/svgs/copy.svg';
  static const String download = 'assets/svgs/download.svg';
  static const String edit = 'assets/svgs/edit.svg';
  static const String emptyCircleImage = 'assets/svgs/empty_circle_image.svg';
  static const String facebookIcon = 'assets/svgs/facebook_icon.svg';
  static const String filterIcon = 'assets/svgs/filter_icon.svg';
  static const String liked = 'assets/svgs/liked.svg';
  static const String megalabIconPurple = 'assets/svgs/megalab_icon_purple.svg';
  static const String megalabIconWhite = 'assets/svgs/megalab_icon_white.svg';
  static const String plus = 'assets/svgs/plus.svg';
  static const String purpleMenu = 'assets/svgs/purple_menu.svg';
  static const String purpleProfile = 'assets/svgs/purple_profile.svg';
  static const String purpleSearch = 'assets/svgs/purple_search.svg';
  static const String share = 'assets/svgs/share.svg';
  static const String telegramIcon = 'assets/svgs/telegram_icon.svg';
  static const String trash = 'assets/svgs/trash.svg';
  static const String twitter = 'assets/svgs/twitter.svg';
  static const String unlike = 'assets/svgs/unlike.svg';
  static const String whatsappIcon = 'assets/svgs/whatsapp_icon.svg';
  static const String whiteMenu = 'assets/svgs/white_menu.svg';
  static const String whiteProfile = 'assets/svgs/white_profile.svg';
  static const String whiteSearch = 'assets/svgs/white_search.svg';
  static const String x = 'assets/svgs/x.svg';
}
